version: '3.8'
services:
  db:
    image: postgres:16
    container_name: db
    hostname: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db